name: Primeiro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Validacao:
  # Maquina Virtual
    runs-on: ubuntu-latest

    # Tarefas para a Validação 
    steps:
      - name: Fazendo o gitclone
        uses: actions/checkout@v4

      - name: Listando o diretório para ver os arquivos
        run: ls -l

      - name: Deixando uma mensagem
        run: echo "Está funcionando o CI"
          echo Add other actions to build,
          echo test, and deploy your project.
